#! /bin/bash
#
# $Author: ee364a11 $
# $Date: 2016-01-12 14:36:14 -0500 (Tue, 12 Jan 2016) $
# $HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364a11/Lab00/Script2 $
# $Revision: 83944 $

for (( I=$1;I>=0; I--))
do
    echo $I
done
exit 0