#! bin/bash
#
# $Author: ee364a11 $
# $Date: 2016-01-12 14:08:26 -0500 (Tue, 12 Jan 2016) $
# $HeadURL: svn+ssh://ece364sv@ecegrid-thin1/home/ecegrid/a/ece364sv/svn/S16/students/ee364a11/Lab00/testheader $
# $Revision: 83839 $